const formFields = [
  { name: "Daire_ID", label: "Daire_ID", type: "text", hidden: true },
  { name: "daire_adi", label: "daire_adi", type: "text", hidden: true },
  { name: "Ilan_Baslik", label: "Başlık", type: "text", required: true },
  { name: "Ilan_Aciklama", label: "Açıklama", type: "text" },
  {
    name: "Ilan_Turu",
    label: "İlan Türü",
    type: "select",
    required: true,
    options: [
      { label: "Satılık", value: "satilik" },
      { label: "Kiralık", value: "kiralik" },
      { label: "Kısa Dönemli Kiralık", value: "kisadonemli_kiralik" },
    ],
  },
  { name: "Fiyat", label: "Fiyat", type: "number", required: true },
  { name: "Depozito", label: "Depozito", type: "number" },
  { name: "Iletisim_Telefon", label: "İletişim Telefon", type: "text" },
  { name: "Iletisim_Email", label: "İletişim Email", type: "email" },
  { name: "Ozellikler", label: "Özellikler", type: "text" },
  { name: "Fotograf_Url", label: "Fotoğraf URL", type: "text" },
  {
    name: "Oda_Sayisi",
    label: "Oda Sayısı",
    type: "select",
    options: [
      { label: "1+0", value: "1+0" },
      { label: "1+1", value: "1+1" },
      { label: "2+1", value: "2+1" },
      { label: "3+1", value: "3+1" },
      { label: "3+2", value: "3+2" },
      { label: "4+1", value: "4+1" },
      { label: "4+2", value: "4+2" },
      { label: "5+1", value: "5+1" },
      { label: "5+2", value: "5+2" },
      { label: "6+1", value: "6+1" },
      { label: "6+2", value: "6+2" },
    ],
  },
  {
    name: "Bulundugu_Kat",
    label: "Bulunduğu Kat",
    type: "select",
    options: [
      { label: "Giriş Altı Kot 4", value: "girisaltikot4" },
      { label: "Giriş Altı Kot 3", value: "girisaltikot3" },
      { label: "Giriş Altı Kot 2", value: "girisaltikot2" },
      { label: "Giriş Altı Kot 1", value: "girisaltikot1" },
      { label: "Bodrum Kat", value: "bodrumkat" },
      { label: "Zemin Kat", value: "zeminkat" },
      { label: "Bahçe Katı", value: "bahcekati" },
      { label: "Giriş Katı", value: "giriskati" },
      { label: "Yüksek Giriş", value: "yuksekgiris" },
      { label: "Çatı Katı", value: "catikati" },
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "7", value: "7" },
      { label: "8", value: "8" },
      { label: "9", value: "9" },
      { label: "10", value: "10" },
      { label: "11", value: "11" },
      { label: "12", value: "12" },
      { label: "13", value: "13" },
      { label: "14", value: "14" },
      { label: "15", value: "15" },
      { label: "16", value: "16" },
      { label: "17", value: "17" },
      { label: "18", value: "18" },
      { label: "19", value: "19" },
      { label: "20", value: "20" },
      { label: "21", value: "21" },
      { label: "22", value: "22" },
      { label: "23", value: "23" },
      { label: "24", value: "24" },
      { label: "25", value: "25" },
      { label: "26", value: "26" },
      { label: "27", value: "27" },
      { label: "28", value: "28" },
      { label: "29", value: "29" },
      { label: "30 ve üzeri", value: "30veuzeri" },
    ],
  },
  { name: "M2", label: "M²", type: "number" },
  {
    name: "Bina_Yasi",
    label: "Bina Yaşı",
    type: "select",
    options: [
      { label: "0", value: "0" },
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5-10 arası", value: "5-10" },
      { label: "11-15 arası", value: "11-15" },
      { label: "16-20 arası", value: "16-20" },
      { label: "21-25 arası", value: "21-25" },
      { label: "26-30 arası", value: "26-30" },
      { label: "31 ve üzeri", value: "31veuzeri" },
    ],
  },
  {
    name: "Kat_Sayisi",
    label: "Kat Sayısı",
    type: "select",
    options: [
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "7", value: "7" },
      { label: "8", value: "8" },
      { label: "9", value: "9" },
      { label: "10", value: "10" },
      { label: "11", value: "11" },
      { label: "12", value: "12" },
      { label: "13", value: "13" },
      { label: "14", value: "14" },
      { label: "15", value: "15" },
      { label: "16", value: "16" },
      { label: "17", value: "17" },
      { label: "18", value: "18" },
      { label: "19", value: "19" },
      { label: "20", value: "20" },
      { label: "21", value: "21" },
      { label: "22", value: "22" },
      { label: "23", value: "23" },
      { label: "24", value: "24" },
      { label: "25", value: "25" },
      { label: "26", value: "26" },
      { label: "27", value: "27" },
      { label: "28", value: "28" },
      { label: "29", value: "29" },
      { label: "30 ve üzeri", value: "30veuzeri" },
    ],
  },
  {
    name: "Mutfak",
    label: "Mutfak",
    type: "select",
    options: [
      { label: "Açık (Amerikan)", value: "acik" },
      { label: "Kapalı", value: "kapali" },
    ],
  },
  {
    name: "Isitma",
    label: "Isıtma",
    type: "select",
    options: [
      { label: "Yok", value: "yok" },
      { label: "Merkezi", value: "merkezi" },
      { label: "Klima", value: "klima" },
      { label: "Kombi(Doğalgaz)", value: "kombidogaz" },
      { label: "Kombi(Elektrik)", value: "kombielektrik" },
      { label: "Yerden Isıtma", value: "yerdenisitma" },
      { label: "Elektrikli", value: "elektrikli" },
      { label: "Soba", value: "soba" },
      { label: "Şömine", value: "somine" },
      { label: "Güneş Enerjisi", value: "gunesenerjisi" },
      { label: "Doğalgaz Sobası", value: "dogalgazsobasi" },
      { label: "Isı Pompası", value: "isipompasi" },
    ],
  },
  {
    name: "Banyo_Sayisi",
    label: "Banyo Sayısı",
    type: "select",
    options: [
      { label: "Yok", value: "yok" },
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "6 üzeri", value: "6uzeri" },
    ],
  },
  {
    name: "Otopark",
    label: "Otopark",
    type: "select",
    options: [
      { label: "Yok", value: "yok" },
      { label: "Açık", value: "acik" },
      { label: "Kapalı", value: "kapali" },
      { label: "Açık ve Kapalı", value: "acikvekapali" },
    ],
  },
  { name: "Asansor", label: "Asansör", type: "boolean" },
  { name: "Esya", label: "Eşyalı", type: "boolean" },
];

export default formFields;
